---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: mydb
spec:
  replicas: 2
  selector:
    matchLabels:
      type: mydb
  template:
    metadata:
      name: mysql-pod
      labels:
        type: mydb
    spec:
      containers:
        - name: mysqldb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test123
...
