apiVersion: v1
kind: Pod
metadata:
  labels:
    type: rproxy
  name: nginx-app
spec:
  containers:
  - name: nginx-liveli
    image: nginx
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      tcpSocket:
         host:
         port: 80
...
