---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: avd
spec:
  containers:
    - name: mynginx
      image: nginx
      volumeMounts:
        - name: my-avd-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: my-avd-volume
      persistentVolumeClaim:
        claimName: my-avdpvc
...
