---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    author: AVD
    type: jenkins
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 7070
...
