---
apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  labels:
    author: AVD
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 7070
...
