---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: posgres-db
    author: AVD
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: test123
        - name: POSTGRES_USER
          value: testuser
        - name: POSTGRES_DB
          value: mydb
...
