---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      - name: mynginx1
        image: nginx
        ports:
          - containerPort: 80
            name: web
        volumeMounts:
          - name: myvolume2
            mountPath: /usr/share/nginx/html

 volumeClaimTemplates:
   - metadata:
     name: myvolume2
     spec:
      acessModes: ["ReadWriteOnce"]
      resources:
       requests:
         storage: 1Gi
...
