---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: db
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mymysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test123
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: myvolume1
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
       name: myvolume1
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
      

