---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    type: webserver
spec:
  containers:
    - name: myhttpd
      image: httpd
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave3
              operator: In
              values:
                - avd3
  tolerations:
    - key: slave3
      operator: Equal
      value: avd3
      effect: NoSchedule
        
...
