---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: AVD
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30014
  selector:
    name: result-app
...
